### ISSUE TITLE
Installation failing on OpenShift 3.7.1 due to nginx permissions

### ISSUE THREAD

**Issue by marziman** [kameshsampath/faas-java-tutorial#1]
Hi @kameshsampath ,

thanks for your instructions and efforts. I just wanted to checkout openwhisk and compare to switch over to it. But if I follow your guide I receive directly this error from nginx pod:

`nginx: [alert] could not open error log file: open() "/var/opt/rh/rh-nginx112/log/nginx/error.log" failed (13: Permission denied)
  | 2018/03/27 16:56:28 [emerg] 1#0: mkdir() "/var/opt/rh/rh-nginx112/lib/nginx/tmp/client_body" failed (13: Permission denied)`

I think this is related to openshift not allowing docker images with root user. But openwhisk is based on the nginx image which needs root. So I run the same command like the minishift addon does:

`oc adm policy add-scc-to-group anyuid system:authenticated`

But no success. 

Can you please support on this..since I cant find out how to run OW.

Thx & BR
Mehmet

**Comment by kameshsampath** [comment]
@marziman - wondering we need to add privileged SCC to your user ?

Tweet Reply
------------

> @mehmet_arziman i guess you need to add previleged user permission to the OpenShift user deploying OW and possibly anyuid permission(safe side). You can check bit.ly/faas-tutorial for some notes on it. Also if on minishift then promisc on is needed

**Comment by kameshsampath** [comment]
it worked and am closing this. for new issues if you find any please open it in redhat-developer-demos/faas-tutorial
